//vendorConstants.js
export const FETCH_VENDOR_DETAILS_REQUEST = 'FETCH_VENDOR_DETAILS_REQUEST';
export const FETCH_VENDOR_DETAILS_SUCCESS = 'FETCH_VENDOR_DETAILS_SUCCESS';
export const FETCH_VENDOR_DETAILS_FAILURE = 'FETCH_VENDOR_DETAILS_FAILURE';

